### ISSUE TITLE
Provide instructions using with build.sbt 

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#14]
SBT 'deprecates' build.scala files. How would we use it with a build.sbt file?

Thanks!

**Comment by marcgrue** [comment]
Yes, a transition to build.sbt is on my todo-list - now officially ;-)

And while doing that it would be nice to see if there was an sbt-mechanism for compiling the generated source code files into a jar during the build process so that we can avoid re-compiling the boilerplate source code files with every project compilation.

**Comment by analytically** [comment]
managed_src?

**Comment by analytically** [comment]
https://github.com/sbt/sbt-buildinfo/blob/master/src/main/scala/sbtbuildinfo/ScalaClassRenderer.scala

**Comment by marcgrue** [comment]
Yes, something like that - and then an additional packaging in a jar... So it's basically two process to complete

**Comment by marcgrue** [comment]
Molecule now uses set 0.13.11 with a build.sbt file. See also the [molecule-demo](https://github.com/scalamolecule/molecule-demo) project for an example of how to use this in your own project.
