### ISSUE TITLE
Schema examples

### ISSUE THREAD

**Issue by analytically** [scalamolecule/molecule#21]
Missing examples from schema:
- transaction functions
- ref to transaction

**Comment by marcgrue** [comment]
On a particular page? Or in general?

**Comment by analytically** [comment]
Just in general. 👍

**Comment by alexflav23** [comment]
Hi @marcgrue,

I'm facing the exact same problem as @analytically here, it would be useful to get some examples here, even if it's just a few links or some test scenarios.

Regards.

**Comment by kevinwright** [comment]
Another +1 from me too

**Comment by kevinwright** [comment]
Another +1 from me too

**Comment by marcgrue** [comment]
Ok, I'll look into it! To get me going, can you help me clarify if you are thinking of 
a) how the schema is transacted,
b) how data is transacted in general,
c) Custom Datomic [database functions](http://docs.datomic.com/database-functions.html),
d) or a combination of all? :-)
Thanks for looking into Molecule!

**Comment by marcgrue** [comment]
Also I'm not sure what you meant with "ref to transaction", Mathias?

**Comment by analytically** [comment]
Relationships are expressed with types (val neighborhood = one[Neighborhood]). How do I generate a `:db.type/ref` (relationship) to a transaction id? Or an entity id of the same type?

**Comment by analytically** [comment]
`When the transactor processes a transaction, it creates a transaction entity to represent it. By default, this entity has one attribute, :db/txInstant, whose value is the instant that the transaction was processed. In addition, every datom in a transaction refers to the transaction entity through the :tx field of datom.`

http://docs.datomic.com/transactions.html

**Comment by marcgrue** [comment]
Thanks, Mathias - I'm getting back to that. In the meanwhile:
a) [Schema transaction](http://www.scalamolecule.org/developer/schema-transaction/) is now expanded - anything missing/unclear?

**Comment by marcgrue** [comment]
Yes, of course! - this is a most useful feature of Datomic that I have actually already been working on in Molecule but not yet finished or documented (have been too focused on stabilizing the core functionalities). Have a look at the [Provenance](https://github.com/scalamolecule/molecule/blob/master/examples/src/test/scala/molecule/examples/dayOfDatomic/Provenance.scala) example (implementing the [Tour of Datomic](http://blog.datomic.com/2013/05/a-whirlwind-tour-of-datomic-query_16.html) tutorial) where I generically add any attributes (like [here](https://github.com/scalamolecule/molecule/blob/master/examples/src/test/scala/molecule/examples/dayOfDatomic/Provenance.scala#L16)) to a single transaction. I still need to test this more and make the auditing capabilities complete. As a POC this is all doable and high on my priority list. In the transformation example in the bottom you can how the Datomic transaction ends up like (though with replaced stable dummy #db/id numbers to show in the test). 

Since any datoms inserted in the same transaction can be found with that transaction id, I don't think we need to explicitly create schema ref's for auditing purposes. I absolutely need this feature myself too, so it's high on my priority list to develop/expand/document now that I feel that there is a broad foundation of core functionality in place.

Was it something along those lines you had in mind?

Along the same lines: 
https://www.jayway.com/2012/06/27/finding-out-who-changed-what-with-datomic/

**Comment by marcgrue** [comment]
@analytically , @alexflav23 , @kevinwright  - did [version 0.8.0](https://github.com/scalamolecule/molecule/releases/tag/v0.8.0) introducing [Tx meta data](http://www.scalamolecule.org/manual/query/txMetaData/) functionality address your request regarding auditing capabilities? 

Also, a very cool new feature is [Composites](http://www.scalamolecule.org/manual/query/composites/).

I'll look into transaction functions as soon as I get more time.

**Comment by analytically** [comment]
Awesome, thanks! We'll be looking into this!

**Comment by marcgrue** [comment]
Various schema definition examples of different types and purposes are now available here:

- [coretests schema definitions](https://github.com/scalamolecule/molecule/tree/master/coretests/src/main/scala/molecule/coretests)
- [examples schema definition](https://github.com/scalamolecule/molecule/tree/master/examples/src/main/scala/molecule/examples)

To answer some of the previous questions in this thread:

A reference to a transaction entity exists in all datoms. In a molecule you can simply get the transaction entity id where an attribute was transacted with `tx`:
```scala
Person.name.tx.get.head === List("Ben", txId)
```
Note that when querying multiple attributes and a transaction entity id then only transactions where all attributes were transacted will match.

You can get the transaction entity id directly from a transaction report:
```scala
val benBirthdayTransactionId: Long = Person(benId).age(43).update.tx
```

Molecule doesn't have a special `ref` option for pointing to transaction entities. But you could always simply make a Namespace called "TxRef" (or what you like) for instance in your schema and then populated it with transaction entity ids since transactions in Datomic are simply - entities!
```scala
Ben.likes("pizza").TxRef(someOtherTxId).save
```
Have a look also at [tx meta data](https://github.com/scalamolecule/molecule/blob/master/coretests/src/test/scala/molecule/coretests/transaction/TxMetaData.scala)!
